name: Build and Release Tauri App

on:
  push:
    branches:
      "master"  # Spustí workflow pouze při tagování (např. v1.0.0)

jobs:
  build:
    runs-on: windows-latest  # Používá nejnovější verzi Windows pro běh akce

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'  # Použijte LTS verzi Node.js

    # Install dependencies
    - name: Install dependencies
      run: |
        npm ci

    # Setup Rust
    - name: Setup Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    # Install Windows dependencies (WebKitGTK)
    - name: Install Windows dependencies
      run: |
        choco install gtk-runtime

    # Install Tauri CLI
    - name: Install Tauri CLI
      run: |
        npm install -g @tauri-apps/cli

    # Build the app
    - name: Build Tauri app
      run: |
        npm run tauri build

    # Create GitHub Release (Pokud chcete automatizovat release)
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/release/bundle/*

    # Optionally you can upload the artifact or send notifications
